# Generated by Django 4.1.1 on 2022-09-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='create',
            name='status',
            field=models.CharField(default='PENDING', max_length=10),
        ),
    ]
